path: F:\Solar Event Detection Project\2nd attempt #absolute path
train: images/train #relative path
val: images/val #relative path
train: test_image
#classes
nc: 3
names: [prominence, sunspot, coronal hole]
